### ISSUE TITLE
Edit button does not show the file but ask you to fork if you don't have a fork

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-io/antora-ui-spring#30]
If I click on the edit button, the link takes me to the edit view of the file on GH (not surprisingly): https://github.com/rwinch/spring-security/edit/antora/main/docs/modules/ROOT/pages/index.adoc

In case I don’t have a fork, this view won’t show me the file but this message: 'You need to fork this repository to propose changes.'
If I have a fork, it edits the file.

I’m wondering if it worth to add an additional view button or a view button instead of edit so that users can see the file and click on edit icon if they want to propose a change: https://github.com/rwinch/spring-security/blob/antora/main/docs/modules/ROOT/pages/index.adoc

This can be useful if users wants to do any of these _without forking_ the repo:
- Troubleshooting: see the GitHub rendered page or the raw contents
- Checking the history of the file or blame
- Browsing the repo
- Commenting the (latest/any) commit on the file

In order to do these, they need to either modify the url or go back to the folder of the file and open the file again.

**Comment by rwinch** [comment]
Thanks for the report.

I do not want to add additional complexity to our code (this would be a customization to Antora) and to the UI elements displayed to our user. The cost of forking a repo to view it is quite minimal in my opinion.

If this is something that needs improvements, then it should be something done through GitHub so that anyone using GitHub can preview and then edit the file.
